name: Dash App Deployment with ngrok

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dash  
        pip install plotly
        pip install pandas

    - name: Run Dash App
      run: |
        python test.py &
        sleep 10  
        curl localhost:9697

    - name: Install ngrok and create tunnel
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} # Assuming you have a secret named NGROK_AUTH_TOKEN
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken $NGROK_AUTH_TOKEN
        ./ngrok http 9697 &
        sleep 10  

    - name: Display ngrok URL
      run: |
        curl http://localhost:4040/api/tunnels | jq ".tunnels[0].public_url"
    
    - name: Keep Alive for 5 min
      run: |
        sleep 300


